# Generated by Django 5.0.7 on 2024-08-22 12:35

import store.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='store\\images', validators=[store.validators.validate_file_size]),
        ),
    ]
