# Generated by Django 5.1.2 on 2024-12-04 18:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_vendorimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.URLField(max_length=500),
        ),
    ]
