# Generated by Django 5.1.5 on 2025-01-22 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0002_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
